version: "3.7"
services:
  app:
    build:
      context: .
      target: prod
    image: example
    container_name: app
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=postgres
      - APP_SCHEMA=public
  db:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
